### ISSUE TITLE
English language not supported? 

### ISSUE THREAD

**Issue by franckflo** [brunocalado/omniscient-die#1]
HI,

this module is a great idea, I use that type of dice for my iRL games actually. I'm using Foundry 9 (latest build) in the Forge with English language. I followed your instructions to setup the module but the dr dice always comes up in portuguese. Is the a setting somewhere to pick the language? I thought it'd default to the same language as Foundry and the System (dnd 5e) but it doesn't seem to be the case. 

In any case, thanks for this module!

**Comment by brunocalado** [comment]
> HI,
> 
> this module is a great idea, I use that type of dice for my iRL games actually. I'm using Foundry 9 (latest build) in the Forge with English language. I followed your instructions to setup the module but the dr dice always comes up in portuguese. Is the a setting somewhere to pick the language? I thought it'd default to the same language as Foundry and the System (dnd 5e) but it doesn't seem to be the case.
> 
> In any case, thanks for this module!

Hi. 
English should work:
![image](https://user-images.githubusercontent.com/4999783/174598496-4b803f32-2fd8-4568-ba18-86ade374f5d0.png)

Can you test with Find the Culprit or in a empty world?

**Comment by franckflo** [comment]
Interestingly, after restarting my server a couple times, the dice started loading in English. I'm all set :). Thanks again.
